- name: Configurar Active Directory
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Instalar AD Domain Services
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes
    
    - name: Promover a Domain Controller
      win_domain:
        dns_domain_name: auto.local
        safe_mode_password: Password123!
      register: domain_install
    
    - name: Reiniciar servidor
      win_reboot:
        reboot_timeout: 600
      when: domain_install.reboot_required
